export default {
    MOUSEMOVE: "MOUSEMOVE",
    WHEEL: "WHEEL",
    MOUSEDOWN: "MOUSEDOWN",
    MOUSEUP: "MOUSEUP",
    CLICK: "CLICK",
    DBLCLICK: "DBLCLICK",
    MOUSEOVER: "MOUSEOVER",
    MOUSEOUT: "MOUSEOUT"
}